export const ITALIAN_PROVINCES: Record<string,{name:string;region:string}> = {
  AG: { name: 'Agrigento', region: 'Sicilia' },
  AL: { name: 'Alessandria', region: 'Piemonte' },
  AN: { name: 'Ancona', region: 'Marche' },
  AO: { name: 'Aosta', region: "Valle d'Aosta" },
  AP: { name: 'Ascoli Piceno', region: 'Marche' },
  AQ: { name: "L'Aquila", region: 'Abruzzo' },
  AR: { name: 'Arezzo', region: 'Toscana' },
  AT: { name: 'Asti', region: 'Piemonte' },
  AV: { name: 'Avellino', region: 'Campania' },
  BA: { name: 'Bari', region: 'Puglia' },
  BG: { name: 'Bergamo', region: 'Lombardia' },
  BI: { name: 'Biella', region: 'Piemonte' },
  BL: { name: 'Belluno', region: 'Veneto' },
  BN: { name: 'Benevento', region: 'Campania' },
  BO: { name: 'Bologna', region: 'Emilia-Romagna' },
  BR: { name: 'Brindisi', region: 'Puglia' },
  BS: { name: 'Brescia', region: 'Lombardia' },
  BT: { name: 'Barletta-Andria-Trani', region: 'Puglia' },
  BZ: { name: 'Bolzano', region: 'Trentino-Alto Adige' },
  CA: { name: 'Cagliari', region: 'Sardegna' },
  CB: { name: 'Campobasso', region: 'Molise' },
  CE: { name: 'Caserta', region: 'Campania' },
  CH: { name: 'Chieti', region: 'Abruzzo' },
  CL: { name: 'Caltanissetta', region: 'Sicilia' },
  CN: { name: 'Cuneo', region: 'Piemonte' },
  CO: { name: 'Como', region: 'Lombardia' },
  CR: { name: 'Cremona', region: 'Lombardia' },
  CS: { name: 'Cosenza', region: 'Calabria' },
  CT: { name: 'Catania', region: 'Sicilia' },
  CZ: { name: 'Catanzaro', region: 'Calabria' },
  EN: { name: 'Enna', region: 'Sicilia' },
  FC: { name: 'Forli-Cesena', region: 'Emilia-Romagna' },
  FE: { name: 'Ferrara', region: 'Emilia-Romagna' },
  FG: { name: 'Foggia', region: 'Puglia' },
  FI: { name: 'Firenze', region: 'Toscana' },
  FM: { name: 'Fermo', region: 'Marche' },
  FR: { name: 'Frosinone', region: 'Lazio' },
  GE: { name: 'Genova', region: 'Liguria' },
  GO: { name: 'Gorizia', region: 'Friuli-Venezia Giulia' },
  GR: { name: 'Grosseto', region: 'Toscana' },
  IM: { name: 'Imperia', region: 'Liguria' },
  IS: { name: 'Isernia', region: 'Molise' },
  KR: { name: 'Crotone', region: 'Calabria' },
  LC: { name: 'Lecco', region: 'Lombardia' },
  LE: { name: 'Lecce', region: 'Puglia' },
  LI: { name: 'Livorno', region: 'Toscana' },
  LO: { name: 'Lodi', region: 'Lombardia' },
  LT: { name: 'Latina', region: 'Lazio' },
  LU: { name: 'Lucca', region: 'Toscana' },
  MB: { name: 'Monza e Brianza', region: 'Lombardia' },
  MC: { name: 'Macerata', region: 'Marche' },
  ME: { name: 'Messina', region: 'Sicilia' },
  MI: { name: 'Milano', region: 'Lombardia' },
  MN: { name: 'Mantova', region: 'Lombardia' },
  MO: { name: 'Modena', region: 'Emilia-Romagna' },
  MS: { name: 'Massa-Carrara', region: 'Toscana' },
  MT: { name: 'Matera', region: 'Basilicata' },
  NA: { name: 'Napoli', region: 'Campania' },
  NO: { name: 'Novara', region: 'Piemonte' },
  NU: { name: 'Nuoro', region: 'Sardegna' },
  OR: { name: 'Oristano', region: 'Sardegna' },
  PA: { name: 'Palermo', region: 'Sicilia' },
  PC: { name: 'Piacenza', region: 'Emilia-Romagna' },
  PD: { name: 'Padova', region: 'Veneto' },
  PE: { name: 'Pescara', region: 'Abruzzo' },
  PG: { name: 'Perugia', region: 'Umbria' },
  PI: { name: 'Pisa', region: 'Toscana' },
  PN: { name: 'Pordenone', region: 'Friuli-Venezia Giulia' },
  PO: { name: 'Prato', region: 'Toscana' },
  PR: { name: 'Parma', region: 'Emilia-Romagna' },
  PT: { name: 'Pistoia', region: 'Toscana' },
  PU: { name: 'Pesaro e Urbino', region: 'Marche' },
  PV: { name: 'Pavia', region: 'Lombardia' },
  PZ: { name: 'Potenza', region: 'Basilicata' },
  RA: { name: 'Ravenna', region: 'Emilia-Romagna' },
  RC: { name: 'Reggio Calabria', region: 'Calabria' },
  RE: { name: 'Reggio Emilia', region: 'Emilia-Romagna' },
  RG: { name: 'Ragusa', region: 'Sicilia' },
  RI: { name: 'Rieti', region: 'Lazio' },
  RM: { name: 'Roma', region: 'Lazio' },
  RN: { name: 'Rimini', region: 'Emilia-Romagna' },
  RO: { name: 'Rovigo', region: 'Veneto' },
  SA: { name: 'Salerno', region: 'Campania' },
  SI: { name: 'Siena', region: 'Toscana' },
  SO: { name: 'Sondrio', region: 'Lombardia' },
  SP: { name: 'La Spezia', region: 'Liguria' },
  SR: { name: 'Siracusa', region: 'Sicilia' },
  SS: { name: 'Sassari', region: 'Sardegna' },
  SU: { name: 'Sulcis Iglesiente', region: 'Sardegna' },
  SV: { name: 'Savona', region: 'Liguria' },
  TA: { name: 'Taranto', region: 'Puglia' },
  TE: { name: 'Teramo', region: 'Abruzzo' },
  TN: { name: 'Trento', region: 'Trentino-Alto Adige' },
  TO: { name: 'Torino', region: 'Piemonte' },
  TP: { name: 'Trapani', region: 'Sicilia' },
  TR: { name: 'Terni', region: 'Umbria' },
  TS: { name: 'Trieste', region: 'Friuli-Venezia Giulia' },
  TV: { name: 'Treviso', region: 'Veneto' },
  UD: { name: 'Udine', region: 'Friuli-Venezia Giulia' },
  VA: { name: 'Varese', region: 'Lombardia' },
  VB: { name: 'Verbano-Cusio-Ossola', region: 'Piemonte' },
  VC: { name: 'Vercelli', region: 'Piemonte' },
  VE: { name: 'Venezia', region: 'Veneto' },
  VI: { name: 'Vicenza', region: 'Veneto' },
  VR: { name: 'Verona', region: 'Veneto' },
  VT: { name: 'Viterbo', region: 'Lazio' },
  VV: { name: 'Vibo Valentia', region: 'Calabria' }
};
