begin;

create table if not exists public.places (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  continent text not null default 'Europa',
  country text not null default 'Italia',
  region text not null,
  city text not null,
  type text not null,
  gf_category text not null default 'Stato da verificare',
  address text not null,
  latitude double precision not null,
  longitude double precision not null,
  phone text not null default '',
  website text not null default '',
  description text not null default '',
  notes text not null default '',
  is_demo boolean not null default false,
  verified boolean not null default false,
  published boolean not null default true,
  delivery_available boolean not null default false,
  direct_delivery boolean not null default false,
  takeaway_available boolean not null default false,
  just_eat_url text not null default '',
  glovo_url text not null default '',
  too_good_to_go_available boolean not null default false,
  too_good_to_go_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists places_location_idx on public.places(country, region, city);
create index if not exists places_type_idx on public.places(type);
create index if not exists places_published_idx on public.places(published);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.set_place_updated_at()
returns trigger language plpgsql security invoker set search_path = ''
as $$ begin new.updated_at = now(); return new; end; $$;

drop trigger if exists places_set_updated_at on public.places;
create trigger places_set_updated_at before update on public.places
for each row execute procedure public.set_place_updated_at();

alter table public.places enable row level security;

drop policy if exists "Published places are public" on public.places;
drop policy if exists "Admins read all places" on public.places;
drop policy if exists "Admins create places" on public.places;
drop policy if exists "Admins update places" on public.places;
drop policy if exists "Admins delete places" on public.places;

create policy "Published places are public" on public.places
for select to anon, authenticated using (published = true);
create policy "Admins read all places" on public.places
for select to authenticated using ((select public.is_admin()));
create policy "Admins create places" on public.places
for insert to authenticated with check ((select public.is_admin()));
create policy "Admins update places" on public.places
for update to authenticated using ((select public.is_admin()))
with check ((select public.is_admin()));
create policy "Admins delete places" on public.places
for delete to authenticated using ((select public.is_admin()));

revoke all on public.places from anon, authenticated;
grant select on public.places to anon, authenticated;
grant insert, update, delete on public.places to authenticated;
grant usage, select on sequence public.places_id_seq to authenticated;

-- Privacy hardening: public clients can read only profile id and nickname, never role.
revoke select on public.profiles from anon, authenticated;
grant select (id, display_name) on public.profiles to anon, authenticated;

commit;
