"use client";
import{FormEvent,useEffect,useState}from"react";import Link from"next/link";import{supabase}from"@/lib/supabase-browser";import type{Place}from"@/types/place";
const empty:any={slug:"",name:"",continent:"Europa",country:"Italia",region:"",city:"",type:"Ristorante",gf_category:"Stato da verificare",address:"",latitude:0,longitude:0,phone:"",website:"",description:"",notes:"",is_demo:false,verified:false,published:true,delivery_available:false,direct_delivery:false,takeaway_available:false,just_eat_url:"",glovo_url:"",too_good_to_go_available:false,too_good_to_go_url:""};
export default function AdminPlaces(){const[allowed,setAllowed]=useState<boolean|null>(null);const[places,setPlaces]=useState<Place[]>([]);const[form,setForm]=useState<any>(empty);const[editingId,setEditingId]=useState<number|null>(null);const[msg,setMsg]=useState("");
async function load(){const{data}=await supabase.from("places").select("*").order("name");setPlaces((data??[])as Place[])}
useEffect(()=>{(async()=>{const{data:s}=await supabase.auth.getSession();if(!s.session){setAllowed(false);return}const{data:p}=await supabase.rpc("is_admin");const ok=p===true;setAllowed(ok);if(ok)load()})()},[]);
function set(key:string,value:any){setForm((f:any)=>({...f,[key]:value}))}function edit(p:Place){setEditingId(p.id);setForm(p);window.scrollTo({top:0,behavior:"smooth"})}function reset(){setEditingId(null);setForm(empty);setMsg("")}
async function save(e:FormEvent){e.preventDefault();setMsg("");const payload={...form,latitude:Number(form.latitude),longitude:Number(form.longitude)};delete payload.id;delete payload.created_at;delete payload.updated_at;const result=editingId?await supabase.from("places").update(payload).eq("id",editingId):await supabase.from("places").insert(payload);if(result.error){setMsg(result.error.message);return}setMsg(editingId?"Locale aggiornato.":"Locale creato.");reset();await load()}
async function remove(id:number){if(!confirm("Eliminare definitivamente questo locale?"))return;const{error}=await supabase.from("places").delete().eq("id",id);if(error)setMsg(error.message);else load()}
if(allowed===null)return<main style={page}>Verifica autorizzazioni...</main>;if(!allowed)return<main style={page}><h1>Accesso negato</h1><p>Questa pagina è riservata agli amministratori.</p><Link href="/">Torna alla home</Link></main>;
const textFields=[['name','Nome'],['slug','Slug'],['continent','Continente'],['country','Nazione'],['region','Regione'],['city','Città'],['type','Tipologia'],['gf_category','Affidabilità GF'],['address','Indirizzo'],['phone','Telefono'],['website','Sito web'],['just_eat_url','URL Just Eat'],['glovo_url','URL Glovo'],['too_good_to_go_url','URL Too Good To Go']];
return<main style={page}><Link href="/">← Home</Link><h1>Pannello admin locali</h1><form onSubmit={save} style={formStyle}><h2>{editingId?"Modifica locale":"Nuovo locale"}</h2>{textFields.map(([k,l])=><label key={k}>{l}<input value={form[k]??''} onChange={e=>set(k,e.target.value)} required={['name','slug','region','city','type','address'].includes(k)} style={input}/></label>)}<label>Latitudine<input type="number" step="any" value={form.latitude} onChange={e=>set('latitude',e.target.value)} required style={input}/></label><label>Longitudine<input type="number" step="any" value={form.longitude} onChange={e=>set('longitude',e.target.value)} required style={input}/></label><label>Descrizione<textarea value={form.description} onChange={e=>set('description',e.target.value)} rows={4} style={input}/></label><label>Note<textarea value={form.notes} onChange={e=>set('notes',e.target.value)} rows={3} style={input}/></label>{['published','verified','is_demo','delivery_available','direct_delivery','takeaway_available','too_good_to_go_available'].map(k=><label key={k}><input type="checkbox" checked={!!form[k]} onChange={e=>set(k,e.target.checked)}/> {k.replaceAll('_',' ')}</label>)}<div><button style={primary}>{editingId?"Salva modifiche":"Crea locale"}</button>{editingId&&<button type="button" onClick={reset} style={secondary}>Annulla</button>}</div></form>{msg&&<p>{msg}</p>}<h2>Locali ({places.length})</h2><div style={{display:"grid",gap:"10px"}}>{places.map(p=><article key={p.id} style={card}><strong>{p.name}</strong> · {p.city} · {p.published?"Pubblicato":"Nascosto"}<div><button onClick={()=>edit(p)}>Modifica</button> <button onClick={()=>remove(p.id)} style={{color:"#b91c1c"}}>Elimina</button> <Link href={`/places/${p.slug}`}>Apri</Link></div></article>)}</div></main>}
const page={maxWidth:"1000px",margin:"0 auto",padding:"32px 20px",fontFamily:"Arial, sans-serif"};const formStyle={display:"grid",gap:"12px",padding:"20px",border:"1px solid #ddd",borderRadius:"10px"};const input={display:"block",width:"100%",boxSizing:"border-box" as const,padding:"9px",marginTop:"4px"};const primary={padding:"10px 16px",background:"#15803d",color:"white",border:0,borderRadius:"6px"};const secondary={padding:"10px 16px",marginLeft:"8px"};const card={padding:"14px",border:"1px solid #ddd",borderRadius:"8px"};
